/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankmng;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Nayana Sunil Ghalme
 */
public class fastcash extends javax.swing.JFrame {
String pin;
    /**
     * Creates new form fastcash
     */
    public fastcash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("       FAST CASH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("select withdrwal amount :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setText("500");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("1000");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("10000");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("100");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton4)
                        .addGap(70, 70, 70)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            String amount = ((javax.swing.JButton) evt.getSource()).getText(); 
              Class.forName("com.mysql.cj.jdbc.Driver");
        String p1 = "jdbc:mysql://localhost/bankSystem";
        Connection cn = DriverManager.getConnection(p1, "root", "nayana@2004");
        Statement st = cn.createStatement();
         Date date = new Date();
         try{
               String query = "SELECT * FROM bank WHERE pin=' +null + '";
        System.out.println("Executing query: " + query);

        // Execute the query
        ResultSet resultset = st.executeQuery(query);
        int balance=0;
        while(resultset.next()){
            if(resultset.getString("type").equals("deposit")){
                balance+=Integer.parseInt(resultset.getString("amount"));
            }else{
                  balance-=Integer.parseInt(resultset.getString("amount"));
            }

         }
        String num="17";
        if(balance<Integer.parseInt(amount)){
             JOptionPane.showMessageDialog(null, "Insufficient Balance");
             return;
        }
        st.executeUpdate("insert into banl values('"+pin+"','"+date+"','withdrwal','"+amount+"'");
        JOptionPane.showMessageDialog(null, "Rs."+amount+"debited");
        
        
       
         }catch(Exception E){
              E.printStackTrace(); 
         }
       
         setVisible(false);
         new Transaction();
            
        } 
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            String amount = ((javax.swing.JButton) evt.getSource()).getText(); 
              Class.forName("com.mysql.cj.jdbc.Driver");
        String p1 = "jdbc:mysql://localhost/bankSystem";
        Connection cn = DriverManager.getConnection(p1, "root", "nayana@2004");
        Statement st = cn.createStatement();
         Date date = new Date();
         try{
               String query = "SELECT * FROM bank WHERE pin='" + pin + "'";
        System.out.println("Executing query: " + query);

        // Execute the query
        ResultSet resultset = st.executeQuery(query);
        int balance=0;
        while(resultset.next()){
            if(resultset.getString("type").equals("deposit")){
                balance+=Integer.parseInt(resultset.getString("amount"));
            }else{
                  balance-=Integer.parseInt(resultset.getString("amount"));
            }

         }
        String num="17";
        if(balance<Integer.parseInt(amount)){
             JOptionPane.showMessageDialog(null, "Insufficient Balance");
             return;
        }
        st.executeUpdate("insert into banl values('"+pin+"','"+date+"','withdrwal','"+amount+"'");
        JOptionPane.showMessageDialog(null, "Rs."+amount+"debited");
        
        
       
         }catch(Exception E){
              E.printStackTrace(); 
         }
       
         setVisible(false);
         new Transaction();
            
        } 
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            String amount = ((javax.swing.JButton) evt.getSource()).getText(); 
              Class.forName("com.mysql.cj.jdbc.Driver");
        String p1 = "jdbc:mysql://localhost/bankSystem";
        Connection cn = DriverManager.getConnection(p1, "root", "nayana@2004");
        Statement st = cn.createStatement();
         Date date = new Date();
         try{
               String query = "SELECT * FROM bank WHERE pin='" + pin + "'";
        System.out.println("Executing query: " + query);

        // Execute the query
        ResultSet resultset = st.executeQuery(query);
        int balance=0;
        while(resultset.next()){
            if(resultset.getString("type").equals("deposit")){
                balance+=Integer.parseInt(resultset.getString("amount"));
            }else{
                  balance-=Integer.parseInt(resultset.getString("amount"));
            }

         }
        String num="17";
        if(balance<Integer.parseInt(amount)){
             JOptionPane.showMessageDialog(null, "Insufficient Balance");
             return;
        }
        st.executeUpdate("insert into banl values('"+pin+"','"+date+"','withdrwal','"+amount+"'");
        JOptionPane.showMessageDialog(null, "Rs."+amount+"debited");
        
        
       
         }catch(Exception E){
              E.printStackTrace(); 
         }
       
         setVisible(false);
         new Transaction();
            
        } 
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            String amount = ((javax.swing.JButton) evt.getSource()).getText(); 
              Class.forName("com.mysql.cj.jdbc.Driver");
        String p1 = "jdbc:mysql://localhost/bankSystem";
        Connection cn = DriverManager.getConnection(p1, "root", "nayana@2004");
        Statement st = cn.createStatement();
         Date date = new Date();
         try{
               String query = "SELECT * FROM bank WHERE pin='" + pin + "'";
        System.out.println("Executing query: " + query);

        // Execute the query
        ResultSet resultset = st.executeQuery(query);
        int balance=0;
        while(resultset.next()){
            if(resultset.getString("type").equals("deposit")){
                balance+=Integer.parseInt(resultset.getString("amount"));
            }else{
                  balance-=Integer.parseInt(resultset.getString("amount"));
            }

         }
        String num="17";
        if(balance<Integer.parseInt(amount)){
             JOptionPane.showMessageDialog(null, "Insufficient Balance");
             return;
        }
        st.executeUpdate("insert into banl values('"+pin+"','"+date+"','withdrwal','"+amount+"'");
        JOptionPane.showMessageDialog(null, "Rs."+amount+"debited");
        
        
       
         }catch(Exception E){
              E.printStackTrace(); 
         }
       
         setVisible(false);
         new Transaction();
            
        } 
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fastcash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
